// // const translations = {
// //   "English": {
// //       "dashboard": "Dashboard",
// //       "menu": "Menu",
// //       "payment": "Payment",
// //       "users": "Waiters",
// //       "usersList": "Waiters List",
// //       "createUser": "Create Waiter",
// //       "orders": "Orders",
// //       "order": "Order",
// //       "manuallyPlaceOrder": "Manual Order",
// //       "productAvailability": "Product's Availability",
// //       "support": "Support",
// //       "dailyReceipt": "Daily Receipt",
// //       "salesStatistic": "Sales Statistics",
// //       "productPerformance": "Products Performance",
// //       "orderManagement": "Order Management",
// //       "CustomerInsights": "Customer Insights",
// //       "revenueAnalysis": "Revenue Analysis",
// //       "inventoryOverview": "Inventory Overview",
// //       "bills": "Bills",
// //       "home": "Home",
// //       "sections": "Sections",
// //       "section": "Section",
// //       "search": "Search",
// //       "newSection": "New section",
// //       "tables": "Tables",
// //       "save":"save",
// //       "cancel":"Cancel",
// //       "searchByTableNumber": "Search by table number",
// //       "actions": "Actions",
// //       "downloadQR": "Download QR code",
// //       "deleteTable": "Delete Table",
// //       "changeQR": "change QR code",
// //       "create": "Create",
// //       "table": "table",
// //       "enterTableNumber": "Enter Table Number",
// //       "new": "New",
// //       "user": "Waiter",
// //       "email": "email",
// //       "active": "active",
// //       "role": "Role",
// //       "fullName": "Full Name",
// //       "password": "Password",
// //       "edit": "Edit",
// //       "update": "Update",
// //       "pending": "Pending",
// //       "preparing": "Preparing",
// //       "completed": "Completed",
// //       "products": "Products",
// //       "product": "Product",
// //       "moveTo": "Move To",
// //       "moveToPreparing" : "Move To Preparing",
// //       "moveToCompleted" : "Move To Completed",
// //       "select": "Select",
// //       "place": "Place",
// //       "close": "close",
// //       "available": "Available",
// //       "previous": "Previous",
// //       "next": "Next",
// //       "request": "Request",
// //       "answer": "Answer",
// //       "decline": "Decline",
// //       "total": "Total",
// //       "revenue": "Revenue",
// //       "price": "Price",
// //       "date": "Date",
// //       "getReceipt": "Get Today's receipt and close orders",
// //       "powered": "Powered with",
// //       "by": "By",
// //       "light": "Light",
// //       "dark": "Dark",
// //       "auto": "Auto",
// //       "account": "Account",
// //       "lock": "Lock",
// //       "selectProducts" : "Select Products",
// //       "noOrders" :"You didn't get any orders for today",
// //       "dailyReceiptBtn" : "Get Today's Receipt and Close Orders"
// //   },
// //   "French": {
// //       "dashboard": "Tableau de bord",
// //       "menu": "Menu",
// //       "payment": "Paiement",
// //       "users": "serveurs",
// //       "usersList": "Liste des serveurs",
// //       "createUser": "Créer un serveurs",
// //       "orders": "Commandes",
// //       "order": "Commande",
// //       "manuallyPlaceOrder": "commande manuelle",
// //       "productAvailability": "Disponibilité des produits",
// //       "support": "Support",
// //       "dailyReceipt": "Reçu quotidien",
// //       "salesStatistic": "Statistiques de ventes",
// //       "productPerformance": "Performance des produits",
// //       "orderManagement": "Gestion des commandes",
// //       "CustomerInsights": "Aperçus clients",
// //       "revenueAnalysis": "Analyse des revenus",
// //       "inventoryOverview": "Vue d'ensemble des stocks",
// //       "bills": "Factures",
// //       "home": "Accueil",
// //       "sections": "Sections",
// //       "section": "Section",
// //       "search": "Rechercher",
// //       "newSection": "Nouvelle section",
// //       "tables": "Tables",
// //       "save":"sauvegarder",
// //       "cancel":"annuler",
// //       "searchByTableNumber": "Rechercher par numéro de table",
// //       "actions": "Actions",
// //       "downloadQR": "Télécharger le code QR",
// //       "deleteTable": "Supprimer la table",
// //       "changeQR": "Changer le code QR",
// //       "create": "Créer",
// //       "table": "table",
// //       "enterTableNumber": "Entrer le numéro de table",
// //       "new": "Nouveau",
// //       "user": "Serveur",
// //       "email": "email",
// //       "active": "actif",
// //       "role": "Rôle",
// //       "fullName": "Nom complet",
// //       "password": "Mot de passe",
// //       "edit": "Modifier",
// //       "update": "Mettre à jour",
// //       "pending": "En attente",
// //       "preparing": "En préparation",
// //       "completed": "Terminé",
// //       "products": "Produits",
// //       "product": "Produit",
// //       "moveTo": "Déplacer vers",
// //       "moveToPreparing" : "passer à la préparation",
// //       "moveToCompleted" : "passer vers Terminé",
// //       "select": "Sélectionner",
// //       "place": "Placer",
// //       "close": "Fermer",
// //       "available": "Disponible",
// //       "previous": "Précédent",
// //       "next": "Suivant",
// //       "request": "Demande",
// //       "answer": "Répondre",
// //       "decline": "Refuser",
// //       "total": "Total",
// //       "revenue": "Revenu",
// //       "price": "Prix",
// //       "date": "Date",
// //       "getReceipt": "Obtenir le reçu d'aujourd'hui et clôturer les commandes",
// //       "powered": "Propulsé avec",
// //       "by": "Par",
// //       "light": "Clair",
// //       "dark": "Sombre",
// //       "auto": "Auto",
// //       "account": "Compte",
// //       "lock": "Verrouiller",
// //       "selectProducts" : "Sélectionner des produits",
// //       "noOrders" :"Vous n'avez reçu aucune commande aujourd'hui",
// //       "dailyReceiptBtn" : "Obtenez le reçu d'aujourd'hui et clôturez les commandes"

// //   },
// //   "Italian": {
// //       "dashboard": "Cruscotto",
// //       "menu": "Menu",
// //       "payment": "Pagamento",
// //       "users": "camerieri",
// //       "usersList": "Elenco camerieri",
// //       "createUser": "Crea cameriere",
// //       "orders": "Ordini",
// //       "order": "Ordine",
// //       "manuallyPlaceOrder": "ordine manuale",
// //       "productAvailability": "Disponibilità dei prodotti",
// //       "support": "Supporto",
// //       "dailyReceipt": "Ricevuta giornaliera",
// //       "salesStatistic": "Statistiche di vendita",
// //       "productPerformance": "Performance dei prodotti",
// //       "orderManagement": "Gestione ordini",
// //       "CustomerInsights": "Approfondimenti clienti",
// //       "revenueAnalysis": "Analisi dei ricavi",
// //       "inventoryOverview": "Panoramica dell'inventario",
// //       "bills": "Fatture",
// //       "home": "Home",
// //       "sections": "Sezioni",
// //       "section": "Sezione",
// //       "search": "Cerca",
// //       "newSection": "Nuova sezione",
// //       "tables": "Tavoli",
// //       "save":"salvare",
// //       "cancel":"annullare",
// //       "searchByTableNumber": "Cerca per numero di tavolo",
// //       "actions": "Azioni",
// //       "downloadQR": "Scarica il codice QR",
// //       "deleteTable": "Elimina tavolo",
// //       "changeQR": "Cambia il codice QR",
// //       "create": "Crea",
// //       "table": "tavolo",
// //       "enterTableNumber": "Inserisci il numero del tavolo",
// //       "new": "Nuovo",
// //       "user": "cameriere",
// //       "email": "email",
// //       "active": "attivo",
// //       "role": "Ruolo",
// //       "fullName": "Nome completo",
// //       "password": "Password",
// //       "edit": "Modifica",
// //       "update": "Aggiorna",
// //       "pending": "In sospeso",
// //       "preparing": "In preparazione",
// //       "completed": "Completato",
// //       "products": "Prodotti",
// //       "product": "Prodotto",
// //       "moveTo": "Sposta in",
// //       "moveToPreparing" : "passare alla preparazione",
// //       "moveToCompleted" : "Sposta a Completato",
// //       "select": "Seleziona",
// //       "place": "Posiziona",
// //       "close": "Chiudi",
// //       "available": "Disponibile",
// //       "previous": "Precedente",
// //       "next": "Successivo",
// //       "request": "Richiesta",
// //       "answer": "Risposta",
// //       "decline": "Rifiuta",
// //       "total": "Totale",
// //       "revenue": "Ricavo",
// //       "price": "Prezzo",
// //       "date": "Data",
// //       "getReceipt": "Ottieni la ricevuta di oggi e chiudi gli ordini",
// //       "powered": "Alimentato con",
// //       "by": "Da",
// //       "light": "Chiaro",
// //       "dark": "Scuro",
// //       "auto": "Auto",
// //       "account": "Account",
// //       "lock": "Blocca",
// //       "selectProducts" : "Seleziona i prodotti",
// //       "noOrders" :"Non hai ricevuto ordini per oggi",
// //       "dailyReceiptBtn" : "Ottieni la ricevuta di oggi e chiudi gli ordini"


// //   }
// // };
// // export default translations;

// const translations = {
//     "English": {
//         "dashboard": "Dashboard",
//         "menu": "Menu",
//         "payment": "Payment",
//         "users": "Waiters",
//         "usersList": "Waiters List",
//         "createUser": "Create Waiter",
//         "orders": "Orders",
//         "order": "Order",
//         "manuallyPlaceOrder": "Manual Order",
//         "productAvailability": "Product's Availability",
//         "support": "Support",
//         "dailyReceipt": "Daily Receipt",
//         "salesStatistic": "Sales Statistics",
//         "productPerformance": "Products Performance",
//         "orderManagement": "Order Management",
//         "CustomerInsights": "Customer Insights",
//         "revenueAnalysis": "Revenue Analysis",
//         "inventoryOverview": "Inventory Overview",
//         "bills": "Bills",
//         "home": "Home",
//         "sections": "Sections",
//         "section": "Section",
//         "search": "Search",
//         "newSection": "New section",
//         "tables": "Tables",
//         "save":"save",
//         "cancel":"Cancel",
//         "searchByTableNumber": "Search by table number",
//         "actions": "Actions",
//         "downloadQR": "Download QR code",
//         "deleteTable": "Delete Table",
//         "changeQR": "change QR code",
//         "create": "Create",
//         "table": "table",
//         "enterTableNumber": "Enter Table Number",
//         "new": "New",
//         "user": "Waiter",
//         "email": "email",
//         "active": "active",
//         "role": "Role",
//         "password": "Password",
//         "edit": "Edit",
//         "update": "Update",
//         "pending": "Pending",
//         "preparing": "Preparing",
//         "completed": "Completed",
//         "products": "Products",
//         "product": "Product",
//         "moveTo": "Move To",
//         "moveToPreparing" : "Move To Preparing",
//         "moveToCompleted" : "Move To Completed",
//         "select": "Select",
//         "place": "Place",
//         "close": "close",
//         "available": "Available",
//         "previous": "Previous",
//         "next": "Next",
//         "request": "Request",
//         "answer": "Answer",
//         "decline": "Decline",
//         "total": "Total",
//         "revenue": "Revenue",
//         "price": "Price",
//         "date": "Date",
//         "getReceipt": "Get Today's receipt and close orders",
//         "powered": "Powered with",
//         "by": "By",
//         "light": "Light",
//         "dark": "Dark",
//         "auto": "Auto",
//         "account": "Account",
//         "lock": "Lock",
//         "selectProducts" : "Select Products",
//         "noOrders" :"You didn't get any orders for today",
//         "dailyReceiptBtn" : "Get Today's Receipt and Close Orders",
//         "CreateClient": "Create Client",
//         "FullName": "Full Name",
//         "Previous": "Previous",
//         "Next": "Next",
//         "NoSupportRequest": "No support Requests for the moment",
//         "Data": "Data",
//         "New": "New",
//         "LockAccount": "Lock Account",
//         "SearchCategories": "Search Categories",
//         "AddNewCategory": "Add New Category",
//         "DailyRevenue": "Daily Revenue",
//         "Today'sRevenue": "Today's Revenue",
//         "WeeklyRevenue": "Weekly Revenue",
//         "CurrentWeekRevenue": "Current Week Revenue",
//         "MonthlyRevenue": "Monthly Revenue",
//         "CurrentMonthRevenue": "Current Month Revenue",
//         "YearlyRevenue": "Yearly Revenue",
//         "RevenueBetween2Dates": "Revenue Between 2 Dates",
//         "RevenueBetweenDates": "Revenue Between Dates",
//         "Export": "Export",
//         "ExporttoPDF": "Export to PDF",
//         "ExporttoExel": "Export to Exel",
//         "Details": "Details",
//         "Day": "Day",
//         "Monday": "Monday",
//         "Tuesday": "Tuesday",
//         "Wednesday": "Wednesday",
//         "Thursday": "Thursday",
//         "Friday": "Friday",
//         "Sturday": "Sturday",
//         "Sunday": "Sunday",
//         "January": "January",
//         "February": "February",
//         "March": "March",
//         "April": "April",
//         "May": "May",
//         "June": "June",
//         "July": "July",
//         "August": "August",
//         "September": "September",
//         "October": "October",
//         "November": "November",
//         "Decemeber": "Decemeber",
//     },
//     "French": {
//         "dashboard": "Tableau de bord",
//         "menu": "Menu",
//         "payment": "Paiement",
//         "users": "serveurs",
//         "usersList": "Liste des serveurs",
//         "createUser": "Créer un serveurs",
//         "orders": "Commandes",
//         "order": "Commande",
//         "manuallyPlaceOrder": "commande manuelle",
//         "productAvailability": "Disponibilité des produits",
//         "support": "Support",
//         "dailyReceipt": "Reçu quotidien",
//         "salesStatistic": "Statistiques de ventes",
//         "productPerformance": "Performance des produits",
//         "orderManagement": "Gestion des commandes",
//         "CustomerInsights": "Aperçus clients",
//         "revenueAnalysis": "Analyse des revenus",
//         "inventoryOverview": "Vue d'ensemble des stocks",
//         "bills": "Factures",
//         "home": "Accueil",
//         "sections": "Sections",
//         "section": "Section",
//         "search": "Rechercher",
//         "newSection": "Nouvelle section",
//         "tables": "Tables",
//         "save":"sauvegarder",
//         "cancel":"annuler",
//         "searchByTableNumber": "Rechercher par numéro de table",
//         "actions": "Actions",
//         "downloadQR": "Télécharger le code QR",
//         "deleteTable": "Supprimer la table",
//         "changeQR": "Changer le code QR",
//         "create": "Créer",
//         "table": "table",
//         "enterTableNumber": "Entrer le numéro de table",
//         "new": "Nouveau",
//         "user": "Serveur",
//         "email": "email",
//         "active": "actif",
//         "role": "Rôle",
//         "password": "Mot de passe",
//         "edit": "Modifier",
//         "update": "Mettre à jour",
//         "pending": "En attente",
//         "preparing": "En préparation",
//         "completed": "Terminé",
//         "products": "Produits",
//         "product": "Produit",
//         "moveTo": "Déplacer vers",
//         "moveToPreparing" : "passer à la préparation",
//         "moveToCompleted" : "passer vers Terminé",
//         "select": "Sélectionner",
//         "place": "Placer",
//         "close": "Fermer",
//         "available": "Disponible",
//         "previous": "Précédent",
//         "next": "Suivant",
//         "request": "Demande",
//         "answer": "Répondre",
//         "decline": "Refuser",
//         "total": "Total",
//         "revenue": "Revenu",
//         "price": "Prix",
//         "date": "Date",
//         "getReceipt": "Obtenir le reçu d'aujourd'hui et clôturer les commandes",
//         "powered": "Propulsé avec",
//         "by": "Par",
//         "light": "Clair",
//         "dark": "Sombre",
//         "auto": "Auto",
//         "account": "Compte",
//         "lock": "Verrouiller",
//         "selectProducts" : "Sélectionner des produits",
//         "noOrders" :"Vous n'avez reçu aucune commande aujourd'hui",
//         "dailyReceiptBtn" : "Obtenez le reçu d'aujourd'hui et clôturez les commandes",
//         "CreateClient": "Créer un client",
//         "FullName": "Nom et prénom",
//         "Previous": "Précédente",
//         "Next": "Suivante",
//         "NoSupportRequest": "Aucune demande d'assistance pour le moment",
//         "Data": "Donnés",
//         "New": "Nouveau",
//         "LockAccount": "Verrouiller le compte",
//         "SearchCategories": "Catégories de recherche",
//         "AddNewCategory": "Ajouter une nouvelle catégorie",
//         "DailyRevenue": "Revenu quotidien",
//         "Today'sRevenue": "Les revenus d'aujourd'hui",
//         "WeeklyRevenue": "Revenu hebdomadaire",
//         "CurrentWeekRevenue": "Revenus de la semaine en cours",
//         "MonthlyRevenue": "Revenu mensuel",
//         "CurrentMonthRevenue": "Revenus du mois en cours",
//         "YearlyRevenue": "Revenu annuel",
//         "RevenueBetween2Dates": "Revenus entre 2 dates",
//         "RevenueBetweenDates": "Revenus entre les dates",
//         "Export": "Exporter",
//         "ExporttoPDF": "Exporter vers PDF",
//         "ExporttoExel": "Exporter vers Excel",
//         "Details": "Détails",
//         "Day": "Jour",
//         "Monday": "lundi",
//         "Tuesday": "Mardi",
//         "Wednesday": "Mercredi",
//         "Thursday": "Jeudi",
//         "Friday": "Vendredi",
//         "Sturday": "Samedi",
//         "Sunday": "Dimanche",
//         "January": "Janvier",
//         "February": "février",
//         "March": "Mars",
//         "April": "Avril",
//         "May": "Mai",
//         "June": "Juin",
//         "July": "Juillet",
//         "August": "Août",
//         "September": "Septembre",
//         "October": "Octobre",
//         "November": "Nouvembre",
//         "Decemeber": "Decembre",
  
//     },
//     "Italian": {
//         "dashboard": "Cruscotto",
//         "menu": "Menu",
//         "payment": "Pagamento",
//         "users": "camerieri",
//         "usersList": "Elenco camerieri",
//         "createUser": "Crea cameriere",
//         "orders": "Ordini",
//         "order": "Ordine",
//         "manuallyPlaceOrder": "ordine manuale",
//         "productAvailability": "Disponibilità dei prodotti",
//         "support": "Supporto",
//         "dailyReceipt": "Ricevuta giornaliera",
//         "salesStatistic": "Statistiche di vendita",
//         "productPerformance": "Performance dei prodotti",
//         "orderManagement": "Gestione ordini",
//         "CustomerInsights": "Approfondimenti clienti",
//         "revenueAnalysis": "Analisi dei ricavi",
//         "inventoryOverview": "Panoramica dell'inventario",
//         "bills": "Fatture",
//         "home": "Home",
//         "sections": "Sezioni",
//         "section": "Sezione",
//         "search": "Cerca",
//         "newSection": "Nuova sezione",
//         "tables": "Tavoli",
//         "save":"salvare",
//         "cancel":"annullare",
//         "searchByTableNumber": "Cerca per numero di tavolo",
//         "actions": "Azioni",
//         "downloadQR": "Scarica il codice QR",
//         "deleteTable": "Elimina tavolo",
//         "changeQR": "Cambia il codice QR",
//         "create": "Crea",
//         "table": "tavolo",
//         "enterTableNumber": "Inserisci il numero del tavolo",
//         "new": "Nuovo",
//         "user": "cameriere",
//         "email": "email",
//         "active": "attivo",
//         "role": "Ruolo",
//         "password": "Password",
//         "edit": "Modifica",
//         "update": "Aggiorna",
//         "pending": "In sospeso",
//         "preparing": "In preparazione",
//         "completed": "Completato",
//         "products": "Prodotti",
//         "product": "Prodotto",
//         "moveTo": "Sposta in",
//         "moveToPreparing" : "passare alla preparazione",
//         "moveToCompleted" : "Sposta a Completato",
//         "select": "Seleziona",
//         "place": "Posiziona",
//         "close": "Chiudi",
//         "available": "Disponibile",
//         "previous": "Precedente",
//         "next": "Successivo",
//         "request": "Richiesta",
//         "answer": "Risposta",
//         "decline": "Rifiuta",
//         "total": "Totale",
//         "revenue": "Ricavo",
//         "price": "Prezzo",
//         "date": "Data",
//         "getReceipt": "Ottieni la ricevuta di oggi e chiudi gli ordini",
//         "powered": "Alimentato con",
//         "by": "Da",
//         "light": "Chiaro",
//         "dark": "Scuro",
//         "auto": "Auto",
//         "account": "Account",
//         "lock": "Blocca",
//         "selectProducts" : "Seleziona i prodotti",
//         "noOrders" :"Non hai ricevuto ordini per oggi",
//         "dailyReceiptBtn" : "Ottieni la ricevuta di oggi e chiudi gli ordini",
//         "CreateClient" : "Crea cliente",
//         "FullName" : "Nome e cognome",
//         "Previous": "Precedente",
//         "Next": "Prossima",
//         "NoSupportRequest": "Nessuna richiesta di supporto al momento",
//         "Data": "Dati",
//         "New": "Nuovo",
//         "LockAccount": "Blocca account",
//         "SearchCategories": "Categorie di ricerca",
//         "AddNewCategory": "Aggiungi nuova categoria",
//         "DailyRevenue": "Entrate giornaliere",
//         "Today'sRevenue": "Fatturato odierno",
//         "WeeklyRevenue": "Ricavi settimanali",
//         "CurrentWeekRevenue": "Ricavi della settimana corrente",
//         "MonthlyRevenue": "Entrate mensili",
//         "CurrentMonthRevenue": "Entrate del mese corrente",
//         "YearlyRevenue": "Ricavi annuali",
//         "RevenueBetween2Dates": "Entrate tra 2 date",
//         "RevenueBetweenDates": "Ricavi tra le date",
//         "Export": "Esportare",
//         "ExporttoPDF": "Esporta in PDF",
//         "ExporttoExel": "Esporta in Excel",
//         "Details": "Dettagli",
//         "Day": "Giorno",
//         "Monday": "Lunedi",
//         "Tuesday": "Martedì",
//         "Wednesday": "Mercoledì",
//         "Thursday": "Giovedì",
//         "Friday": "Venerdì",
//         "Sturday": "Sabato",
//         "Sunday": "Domenica",
//         "January": "Gennaio",
//         "February": "Febbraio",
//         "March": "Marzo",
//         "April": "Aprile",
//         "May": "Maggio",
//         "June": "Giugno",
//         "July": "Luglio",
//         "August": "Agosto",
//         "September": "settembre",
//         "October": "ottobre",
//         "November": "November",
//         "Decemeber": "Dicembre",
//       }
//   };
//   export default translations;

const translations = {
    "English": {
        "dashboard": "Dashboard",
        "menu": "Menu",
        "payment": "Payment",
        "users": "Waiters",
        "usersList": "Waiters List",
        "createUser": "Create Waiter",
        "orders": "Orders",
        "order": "Order",
        "manuallyPlaceOrder": "Manual Order",
        "productAvailability": "Product's Availability",
        "support": "Support",
        "dailyReceipt": "Daily Receipt",
        "salesStatistic": "Sales Statistics",
        "productPerformance": "Products Performance",
        "orderManagement": "Order Management",
        "CustomerInsights": "Customer Insights",
        "revenueAnalysis": "Revenue Analysis",
        "inventoryOverview": "Inventory Overview",
        "bills": "Bills",
        "home": "Home",
        "sections": "Sections",
        "section": "Section",
        "search": "Search",
        "newSection": "New section",
        "tables": "Tables",
        "save":"save",
        "cancel":"Cancel",
        "searchByTableNumber": "Search by table number",
        "actions": "Actions",
        "downloadQR": "Download QR code",
        "deleteTable": "Delete Table",
        "changeQR": "change QR code",
        "create": "Create",
        "table": "table",
        "enterTableNumber": "Enter Table Number",
        "new": "New",
        "user": "Waiter",
        "email": "email",
        "active": "active",
        "role": "Role",
        "password": "Password",
        "edit": "Edit",
        "update": "Update",
        "pending": "Pending",
        "preparing": "Preparing",
        "completed": "Completed",
        "products": "Products",
        "product": "Product",
        "moveTo": "Move To",
        "moveToPreparing" : "Move To Preparing",
        "moveToCompleted" : "Move To Completed",
        "select": "Select",
        "place": "Place",
        "close": "close",
        "available": "Available",
        "previous": "Previous",
        "next": "Next",
        "request": "Request",
        "answer": "Answer",
        "decline": "Decline",
        "total": "Total",
        "revenue": "Revenue",
        "price": "Price",
        "date": "Date",
        "getReceipt": "Get Today's receipt and close orders",
        "powered": "Powered with",
        "by": "By",
        "light": "Light",
        "dark": "Dark",
        "auto": "Auto",
        "account": "Account",
        "lock": "Lock",
        "selectProducts" : "Select Products",
        "noOrders" :"You didn't get any orders for today",
        "dailyReceiptBtn" : "Get Today's Receipt and Close Orders",
        "CreateClient": "Create Client",
        "FullName": "Full Name",
        "Previous": "Previous",
        "Next": "Next",
        "Nosupportrequestsatthemoment": "No support requests at the moment",
        "Data": "Data",
        "New": "New",
        "LockAccount": "Lock Account",
        "SearchCategories": "Search Categories",
        "AddNewCategory": "Add New Category",
        "DailyRevenue": "Daily Revenue",
        "Today'sRevenue": "Today's Revenue",
        "WeeklyRevenue": "Weekly Revenue",
        "CurrentWeekRevenue": "Current Week Revenue",
        "MonthlyRevenue": "Monthly Revenue",
        "CurrentMonthRevenue": "Current Month Revenue",
        "YearlyRevenue": "Yearly Revenue",
        "RevenueBetween2Dates": "Revenue Between 2 Dates",
        "RevenueBetweenDates": "Revenue Between Dates",
        "Export": "Export",
        "ExporttoPDF": "Export to PDF",
        "ExporttoExel": "Export to Exel",
        "Details": "Details",
        "Day": "Day",
        "Monday": "Monday",
        "Tuesday": "Tuesday",
        "Wednesday": "Wednesday",
        "Thursday": "Thursday",
        "Friday": "Friday",
        "Sturday": "Sturday",
        "Sunday": "Sunday",
        "January": "January",
        "February": "February",
        "March": "March",
        "April": "April",
        "May": "May",
        "June": "June",
        "July": "July",
        "August": "August",
        "September": "September",
        "October": "October",
        "November": "November",
        "Decemeber": "Decemeber",
        "Sold": "Sold",
        "month": "month",
        "Year": "Year",
        "SelectEndDate": "Select End Date",
        "MostSoldProducts": "Most Sold Products",
        "SelectStartDate": "Select Start Date",
        "Exel": "Exel",
        "ProductsRating": "Products Rating",
        "ProductRatings": "Product Ratings",
        "ProductName": "Product Name",
        "NumberofRaters": "Number of Raters",
        "Page": "Page",
        "of": "of",
        "OrderStatusOverview": "Order Status Overview",
        "TimeSpenton": "Time Spent on",
        "mins": "mins",
        "AverageProcessingTime": "Average Processing Time",
        "StartDate": "Start Date",
        "EndDate": "End Date",
        "GetAverageTime": "Get Average Time",
        "OrderCraftBill": "Order Craft Bill",
        "Balance": "Balance",
        "Paid": "Paid",
        "TotalAmount": "Total Amount",
        "BillHistoryPayment": "Bill History Payment",
        "Notransactionsfoundforthisbill": "No transactions found for this bill",
  
        
        
  
    },
    "French": {
        "dashboard": "Tableau de bord",
        "menu": "Menu",
        "payment": "Paiement",
        "users": "serveurs",
        "usersList": "Liste des serveurs",
        "createUser": "Créer un serveurs",
        "orders": "Commandes",
        "order": "Commande",
        "manuallyPlaceOrder": "commande manuelle",
        "productAvailability": "Disponibilité des produits",
        "support": "Support",
        "dailyReceipt": "Reçu quotidien",
        "salesStatistic": "Statistiques de ventes",
        "productPerformance": "Performance des produits",
        "orderManagement": "Gestion des commandes",
        "CustomerInsights": "Aperçus clients",
        "revenueAnalysis": "Analyse des revenus",
        "inventoryOverview": "Vue d'ensemble des stocks",
        "bills": "Factures",
        "home": "Accueil",
        "sections": "Sections",
        "section": "Section",
        "search": "Rechercher",
        "newSection": "Nouvelle section",
        "tables": "Tables",
        "save":"sauvegarder",
        "cancel":"annuler",
        "searchByTableNumber": "Rechercher par numéro de table",
        "actions": "Actions",
        "downloadQR": "Télécharger le code QR",
        "deleteTable": "Supprimer la table",
        "changeQR": "Changer le code QR",
        "create": "Créer",
        "table": "table",
        "enterTableNumber": "Entrer le numéro de table",
        "new": "Nouveau",
        "user": "Serveur",
        "email": "email",
        "active": "actif",
        "role": "Rôle",
        "password": "Mot de passe",
        "edit": "Modifier",
        "update": "Mettre à jour",
        "pending": "En attente",
        "preparing": "En préparation",
        "completed": "Terminé",
        "products": "Produits",
        "product": "Produit",
        "moveTo": "Déplacer vers",
        "moveToPreparing" : "passer à la préparation",
        "moveToCompleted" : "passer vers Terminé",
        "select": "Sélectionner",
        "place": "Placer",
        "close": "Fermer",
        "available": "Disponible",
        "previous": "Précédent",
        "next": "Suivant",
        "request": "Demande",
        "answer": "Répondre",
        "decline": "Refuser",
        "total": "Total",
        "revenue": "Revenu",
        "price": "Prix",
        "date": "Date",
        "getReceipt": "Obtenir le reçu d'aujourd'hui et clôturer les commandes",
        "powered": "Propulsé avec",
        "by": "Par",
        "light": "Clair",
        "dark": "Sombre",
        "auto": "Auto",
        "account": "Compte",
        "lock": "Verrouiller",
        "selectProducts" : "Sélectionner des produits",
        "noOrders" :"Vous n'avez reçu aucune commande aujourd'hui",
        "dailyReceiptBtn" : "Obtenez le reçu d'aujourd'hui et clôturez les commandes",
        "CreateClient": "Créer un client",
        "FullName": "Nom et prénom",
        "Previous": "Précédente",
        "Next": "Suivante",
        "Nosupportrequestsatthemoment": "Aucune demande d'assistance pour le moment",
        "Data": "Donnés",
        "New": "Nouveau",
        "LockAccount": "Verrouiller le compte",
        "SearchCategories": "Catégories de recherche",
        "AddNewCategory": "Ajouter une nouvelle catégorie",
        "DailyRevenue": "Revenu quotidien",
        "Today'sRevenue": "Les revenus d'aujourd'hui",
        "WeeklyRevenue": "Revenu hebdomadaire",
        "CurrentWeekRevenue": "Revenus de la semaine en cours",
        "MonthlyRevenue": "Revenu mensuel",
        "CurrentMonthRevenue": "Revenus du mois en cours",
        "YearlyRevenue": "Revenu annuel",
        "RevenueBetween2Dates": "Revenus entre 2 dates",
        "RevenueBetweenDates": "Revenus entre les dates",
        "Export": "Exporter",
        "ExporttoPDF": "Exporter vers PDF",
        "ExporttoExel": "Exporter vers Excel",
        "Details": "Détails",
        "Day": "Jour",
        "Monday": "lundi",
        "Tuesday": "Mardi",
        "Wednesday": "Mercredi",
        "Thursday": "Jeudi",
        "Friday": "Vendredi",
        "Sturday": "Samedi",
        "Sunday": "Dimanche",
        "January": "Janvier",
        "February": "février",
        "March": "Mars",
        "April": "Avril",
        "May": "Mai",
        "June": "Juin",
        "July": "Juillet",
        "August": "Août",
        "September": "Septembre",
        "October": "Octobre",
        "November": "Nouvembre",
        "Decemeber": "Decembre",
        "Sold": "Vendu",
        "month": "mois",
        "Year": "Année",
        "SelectEndDate": "Sélectionnez la date de fin",
        "MostSoldProducts": "Produits les plus vendus",
        "SelectStartDate": "Sélectionnez la date de début",
        "Exel": "Exel",
        "ProductsRating": "Évaluation des produits",
        "ProductRatings": "Évaluations des produits",
        "ProductName": "Nom du produit",
        "NumberofRaters": "Nombre d'évaluateurs",
        "Page": "Page",
        "of": "de",
        "OrderStatusOverview": "Aperçu du statut de la commande",
        "TimeSpenton": "Temps passé sur",
        "mins": "minutes",
        "AverageProcessingTime": "Temps de traitement moyen",
        "StartDate": "Date de début",
        "EndDate": "Date de fin",
        "GetAverageTime": "Obtenir le temps moyen",
        "OrderCraftBill": "Order Craft Facture",
        "Balance": "Équilibre",
        "Paid": "Payé",
        "TotalAmount": "Montant total",
        "BillHistoryPayment": "Paiement de l'historique des factures",
        "Notransactionsfoundforthisbill": "Aucune transaction trouvée pour cette facture",
  
    },
    "Italian": {
        "dashboard": "Cruscotto",
        "menu": "Menu",
        "payment": "Pagamento",
        "users": "camerieri",
        "usersList": "Elenco camerieri",
        "createUser": "Crea cameriere",
        "orders": "Ordini",
        "order": "Ordine",
        "manuallyPlaceOrder": "ordine manuale",
        "productAvailability": "Disponibilità dei prodotti",
        "support": "Supporto",
        "dailyReceipt": "Ricevuta giornaliera",
        "salesStatistic": "Statistiche di vendita",
        "productPerformance": "Performance dei prodotti",
        "orderManagement": "Gestione ordini",
        "CustomerInsights": "Approfondimenti clienti",
        "revenueAnalysis": "Analisi dei ricavi",
        "inventoryOverview": "Panoramica dell'inventario",
        "bills": "Fatture",
        "home": "Home",
        "sections": "Sezioni",
        "section": "Sezione",
        "search": "Cerca",
        "newSection": "Nuova sezione",
        "tables": "Tavoli",
        "save":"salvare",
        "cancel":"annullare",
        "searchByTableNumber": "Cerca per numero di tavolo",
        "actions": "Azioni",
        "downloadQR": "Scarica il codice QR",
        "deleteTable": "Elimina tavolo",
        "changeQR": "Cambia il codice QR",
        "create": "Crea",
        "table": "tavolo",
        "enterTableNumber": "Inserisci il numero del tavolo",
        "new": "Nuovo",
        "user": "cameriere",
        "email": "email",
        "active": "attivo",
        "role": "Ruolo",
        "password": "Password",
        "edit": "Modifica",
        "update": "Aggiorna",
        "pending": "In sospeso",
        "preparing": "In preparazione",
        "completed": "Completato",
        "products": "Prodotti",
        "product": "Prodotto",
        "moveTo": "Sposta in",
        "moveToPreparing" : "passare alla preparazione",
        "moveToCompleted" : "Sposta a Completato",
        "select": "Seleziona",
        "place": "Posiziona",
        "close": "Chiudi",
        "available": "Disponibile",
        "previous": "Precedente",
        "next": "Successivo",
        "request": "Richiesta",
        "answer": "Risposta",
        "decline": "Rifiuta",
        "total": "Totale",
        "revenue": "Ricavo",
        "price": "Prezzo",
        "date": "Data",
        "getReceipt": "Ottieni la ricevuta di oggi e chiudi gli ordini",
        "powered": "Alimentato con",
        "by": "Da",
        "light": "Chiaro",
        "dark": "Scuro",
        "auto": "Auto",
        "account": "Account",
        "lock": "Blocca",
        "selectProducts" : "Seleziona i prodotti",
        "noOrders" :"Non hai ricevuto ordini per oggi",
        "dailyReceiptBtn" : "Ottieni la ricevuta di oggi e chiudi gli ordini",
        "CreateClient" : "Crea cliente",
        "FullName" : "Nome e cognome",
        "Previous": "Precedente",
        "Next": "Prossima",
        "Nosupportrequestsatthemoment": "Nessuna richiesta di supporto al momento",
        "Data": "Dati",
        "New": "Nuovo",
        "LockAccount": "Blocca account",
        "SearchCategories": "Categorie di ricerca",
        "AddNewCategory": "Aggiungi nuova categoria",
        "DailyRevenue": "Entrate giornaliere",
        "Today'sRevenue": "Fatturato odierno",
        "WeeklyRevenue": "Ricavi settimanali",
        "CurrentWeekRevenue": "Ricavi della settimana corrente",
        "MonthlyRevenue": "Entrate mensili",
        "CurrentMonthRevenue": "Entrate del mese corrente",
        "YearlyRevenue": "Ricavi annuali",
        "RevenueBetween2Dates": "Entrate tra 2 date",
        "RevenueBetweenDates": "Ricavi tra le date",
        "Export": "Esportare",
        "ExporttoPDF": "Esporta in PDF",
        "ExporttoExel": "Esporta in Excel",
        "Details": "Dettagli",
        "Day": "Giorno",
        "Monday": "Lunedi",
        "Tuesday": "Martedì",
        "Wednesday": "Mercoledì",
        "Thursday": "Giovedì",
        "Friday": "Venerdì",
        "Sturday": "Sabato",
        "Sunday": "Domenica",
        "January": "Gennaio",
        "February": "Febbraio",
        "March": "Marzo",
        "April": "Aprile",
        "May": "Maggio",
        "June": "Giugno",
        "July": "Luglio",
        "August": "Agosto",
        "September": "settembre",
        "October": "ottobre",
        "November": "November",
        "Decemeber": "Dicembre",
        "Sold": "Venduto",
        "month": "mese",
        "Year": "Anno",
        "SelectEndDate": "Seleziona Data di fine",
        "MostSoldProducts": "Prodotti più venduti",
        "SelectStartDate": "Seleziona Data di inizio",
        "Exel": "Eccel",
        "ProductsRating": "Valutazione dei prodotti",
        "ProductRatings": "Valutazioni del prodotto",
        "ProductName": "Nome prodotto",
        "NumberofRaters": "Numero di valutatori",
        "Page": "Pagina",
        "of": "Di",
        "OrderStatusOverview": "Panoramica sullo stato dell'ordine",
        "TimeSpenton": "Tempo speso",
        "mins": "min",
        "AverageProcessingTime": "Tempo medio di elaborazione",
        "StartDate": "Data di inizio",
        "EndDate": "Data di fine",
        "GetAverageTime": "Ottieni il tempo medio",
        "OrderCraftBill": "Order Craft fattura",
        "Balance": "Bilancia",
        "Paid": "Pagato",
        "TotalAmount": "Importo totale",
        "BillHistoryPayment": "Pagamento dello storico delle fatture",
        "Notransactionsfoundforthisbill": "Nessuna transazione trovata per questa fattura",
  
      }
  };
  export default translations;